### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by ThomasFaria** [InseeFrLab/satellite-images-train#22]
**Preprocessing** : 
- [ ] Améliorer le preprocessing sur les nuages (regarder les seuils s'ils sont bons ou pas)
- [ ] Utiliser Open Buildings pour labeliser les données plutôt que la BDTopo 

**Train** : 
- [ ]  Rajouter des filtres avant l'entrainement (proportion d'images sans habitation gardée)
- [ ]  Entrainer un bon modèle @tomseimandi (B05 Segformer) 
- [ ] Tester le modèle de l'IGN

**Evaluation** :

- [ ] Créer un repo avec une API qui récupe le modèle sur MLflow (satellite-images-inference)
- [ ] Faire une fonction que prends une image test et renvoie la prédiction du modèle. 
- [ ] Faire des fonctions qui calculent des métriques plus fines sur les images de test (dont métrique pour le RP) 
- [ ] Comparer les prédictions et les masques BDTOPO
- [ ]
